dist: trusty
sudo: required
language: c
compiler:
  - gcc
  - clang
env:
  - RUBYLIB=/usr/lib/ruby/vendor_ruby:/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.3.0
before_install:
  - sudo apt-get update
  - sudo apt-get -y install rake bison git gperf automake m4  autoconf libtool cmake pkg-config libcunit1-dev ragel
script:
  - make setup
  - make test
