dist: trusty
language: c
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - g++
    - rake
    - bison
    - git 
    - gperf
    - automake
    - m4
    - autoconf
    - libtool
    - cmake
    - pkg-config
    - libcunit1-dev
    - ragel
script:
  - make setup
  - make mruby
  - make test
